[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    -v
    --html=reports/report.html
    --self-contained-html

markers =
    login: Login test cases
    product: Product test cases
    cart: Cart test cases